// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlvzskjtyfhhmwdegiuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdnpza2p0eWZoaG13ZGVnaXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzQ1NzEsImV4cCI6MjA2MjIxMDU3MX0.N3iIuMsi3w00X2ARBDrvIc6O3LZ2oFa75FAaAaoE130";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);